### ISSUE TITLE
Troubleshooting Dropwizard Metric Reporter

### ISSUE THREAD

**Issue by mulloymorrow** [coursera/metrics-datadog#52]
I have a simple dropwizard app with the dropwizard-metrics-datadog reporter configured. However, not seeing any metrics sent to my datadog agent. I can confirm that manually sending metrics and events to the locally running datadog agent results in data sent to Datadog. So it seems the issue is isolated to the java reporter sending datagrams to the agent over UDP. 

Dropwizard App Metrics configured as: 
```
metrics:
#  frequency: 1 minute                       # Default is 1 second.
  reporters:
    - type: datadog
      transport:
        type: udp
        prefix: "simility-decision-ingress"                            # Optional. Default is (empty)
        statsdHost: "localhost"             # Optional. Default is "localhost"
        port: 8125
    - type: console
      timeZone: UTC
```

The ConsoleReporter works as expected: 
```
jvm.memory.heap.committed
             value = 242745344
jvm.memory.heap.init
             value = 268435456
jvm.memory.heap.max
             value = 3817865216
jvm.memory.heap.usage
             value = 0.01301376690611804
jvm.memory.heap.used
             value = 49684808
jvm.memory.non-heap.committed
             value = 46792704
jvm.memory.non-heap.init
             value = 2555904
```

Is there a way to intercept or log what the datadog reporter is sending or suppose to send?
