### ISSUE TITLE
Tag Expansion Documentation is Unclear

### ISSUE THREAD

**Issue by MusikPolice** [coursera/metrics-datadog#53]
I'm a bit confused on how to use the tag expansion feature to add tags to a metric. I have a class that contains a bunch of HTTP endpoints, each decorated with an `@Timed` annotation. I'd like to give each of these endpoints the same metric name, and differentiate them by tag, so that I can display them in a Top List on my DataDog dashboard.

The documentation says that the metric name syntax looks like `[tagName:tagValue,tagName:tagValue,...]`, but when I modified my annotation to look like `@Timed("endpoint [tagName:someEndpoint]")`, neither the metric `endpoint` nor the tag `someEndpoint` showed up in DataDog.

Am I missing something? Can you provide a code example for what this syntax actually looks like?

For reference, I added the library to my project using a pom file entry:
```
<dependency>
	<groupId>org.coursera</groupId>
	<artifactId>dropwizard-metrics-datadog</artifactId>
	<version>1.1.5</version>
</dependency>
```
and I enabled sending metrics with some config in my dropwizard project:
```
metrics:
    frequency: 10 seconds
    reporters:
        - type: datadog
          transport:
            type: udp
          excludes:
            - jvm.
            - org.eclipse.jetty.
```
