### ISSUE TITLE
Global tags are not available on Datadog

### ISSUE THREAD

**Issue by homerovalle** [coursera/metrics-datadog#54]
I've tried sending some tags at the reporting level using the following config:

```
metrics:
  frequency: 1 minute
  reporters:
    - type: datadog
      host: ${env.HOSTNAME}
      tags:
        - env:${env.ENV!'noenv'}
        - app:myapp
        - version:${env.BUILD_VERSION!'noversion'}
      transport:
        type: http
        apiKey: ${env.DATADOG_API_KEY}
```

But I don't see any tag when looking at the datadog HOSTNAME used.

Thanks!
