### ISSUE TITLE
Missing Property 'type' when implementing CustomMetricNameFormatter 

### ISSUE THREAD

**Issue by aw8888** [coursera/metrics-datadog#74]
Hi there, I am trying to implement a CustomMetricNameFormatter. I have followed the steps stated on https://github.com/coursera/metrics-datadog but I am running into a yaml parser error on startup.

The error is: 
` * Failed to parse configuration at: metrics.reporters.metricNameFormatter; Unexpected token (VALUE_STRING), expected FIELD_NAME: missing property 'type' that is to contain type id  (for class org.coursera.metrics.datadog.MetricNameFormatterFactory) at [Source: N/A; line: -1, column: -1] (through reference chain: com.test.example.configuration.AppConfiguration["metrics"]->io.dropwizard.metrics.MetricsFactory["reporters"]->io.dropwizard.metrics.DatadogReporterFactory["metricNameFormatter"])`

My config.yaml
```
 metrics:
  frequency: 1 minute
  reporters:
    - type: datadog
      metricNameFormatter: custom
```

Please let me know if you have any suggestions. Thank you for your time.

**Comment by aw8888** [comment]
```
Solved the issue, had to change config.yaml to:

metrics:
  frequency: 1 minute
  reporters:
    - type: datadog
      metricNameFormatter:
        type: custom
```
