### ISSUE TITLE
Filter per metric and expansion

### ISSUE THREAD

**Issue by fabienrenaud** [coursera/metrics-datadog#83]
metric-datadog allows filtering metrisc by name using a `MetricFilter`. This feature should be extended to allow filtering of expansions per metric.

Example
---------
 
 * meter: "httpResCode[endpoint={endpoint},resCode={resCode}]"
 * timer: "httpRequests[endpoint={endpoint}]"
 * whitelisted default expansions: count, p95, p99

The reporter will send to datadog:

 * httpRequests.count[endpoint={endpoint}]
 * httpRequests.p95[endpoint={endpoint}]
 * httpRequests.p99[endpoint={endpoint}]
 * httpResCode.count[endpoint={endpoint},resCode={resCode}]

However, `httpRequests.count` is unnecessary since i can get that count by summing the counts of all resCodes meters (and do that in datadog).

`MetricFilter` only provides filtering by names defined in the metrics API. It would be more convenient to filter by metric name that will be sent to datadog (just before sending it).

**Comment by nickdella** [comment]
Thanks for the write up, @fabienrenaud !  Could you better state your motivation for this request? As stated, I don't see a big benefit in filtering `httpRequests.count` just because it's redundant. That said, I do see tag filtering as useful, especially if you have an application producing a large or unbounded set of tag values for which you'd like to whitelist only the top 10-20 values.

In any case, it's unlikely I'll personally have any time to work on this in the next couple months. PRs are welcome, of course. The codebase is fairly well-test and readable IMO :)

**Comment by qualidafial** [comment]
Datadog pricing is the issue where I work. Every VM or container is allocated a certain number of unique metrics (including tags!). Dropwizard produces so many metrics out of the box that we're nearly over budget before adding any metrics of our own.

**Comment by qualidafial** [comment]
@adamhonen you can already restrict the metric suffixes with the `expansions` config option.

**Comment by qualidafial** [comment]
Example config:

```yml
metrics:
  reporters:
    - type: datadog
      expansions:
        - COUNT
        - MEAN
        - MEDIAN
        - P99
```

**Comment by adamhonen** [comment]
Yeah, I guess my example is simple enough that it could be handled that way.
I was thinking of more elaborate cases where you might want different expansions for different metrics.
That's at least how I understood the initial comment.

**Comment by qualidafial** [comment]
I agree.

I think I'd prefer a solution that used the existing `MetricFilter` scaffolding, and just exposed a couple out-of-the-box filters we could chain together--e.g. whitelist, blacklist, regex matching.

**Comment by qualidafial** [comment]
So.. it looks like this is already provided by dropwizard-metrics:

```yml
metrics:
  reporters:
    - type: datadog
      expansions:
      - COUNT
      - MEAN
      - MEDIAN
      - P99
      useRegexFilters: true
      includes:
      - "myapp.*"
      - "jvm\\.attribute\\.uptime.*"
      - "jvm\\.gc.*"
      - "jvm\\.memory.*"
      excludes:
      - "jvm\\.memory\\.pools.*"
```

The include and excludes are matched against the entire metric name (including tags), so you want to add a `.*` prefix and/or suffix depending on whether you want to match metric names that start with, end with, or just contain some pattern.
